name: 构建 Docker 镜像

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 1 * *'
    
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v3
      
      # 设置 QEMU
      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v2
      
      # 设置 Docker Buildx
      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录到 Docker Hub
      - name: 登录到 Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # 构建并推送 Docker 镜像
      - name: 构建 Docker 镜像
        if: ${{ env.status == 'success' }}
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            superng6/bbr:latest

